name: Node CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [6.0.0]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci
      run: npm ci
    - name: npm lint
      run: npm run lint
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [6.0.0]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci
      run: npm ci
    - name: npm build
      run: npm run build
      
