name: Node CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm ci
      run: npm ci
    - name: npm lint
      run: npm run lint
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 6.0.0
      uses: actions/setup-node@v1
      with:
        node-version: 6.0.0
    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [6.0.0, 7.6.0]

  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - name: npm install
  #     run: npm install
  #   - name: npm build
  #     run: npm run build
  #   - name: npm test
  #     run: npm run test
  #   - uses: codecov/codecov-action@v1
  #     with:
  #       token: ${{ secrets.CODECOV_TOKEN }} #required
  #       file: ./coverage.xml #optional
  #       flags: unittests #optional
  #       yml: ./codecov.yml #optional
  #       fail_ci_if_error: true #optional (default = false):
